### Program Definitions ###
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher
$mainMod = SUPER


### Auto-start Settings ###
# Run these tools in the background
exec-once = waybar
exec-once = mako
exec-once = fcitx5 -d
exec-once = swww-daemon
exec-once = ~/scripts/discord-ipc-link.sh

# クリップボード履歴の保存
exec-once = wl-paste --type text --watch cliphist store # テキスト
exec-once = wl-paste --type image --watch cliphist store # 画像

# Moving wallpapers
$wallpaper_main = ~/Pictures/wallpapers/kaguya.png
$wallpaper_sub  = ~/Pictures/wallpapers/moonflower.mp4

exec-once = mpvpaper -o "no-audio --loop" DP-2 $wallpaper_main
exec-once = mpvpaper -o "no-audio --loop --panscan=1.0 --video-align-x=0.25" HDMI-A-1 $wallpaper_sub


### Environment Variables ###
# Cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Japanese input (fcitx5) and Firefox Wayland support
env = XMODIFIERS,@im=fcitx
env = QT_IM_MODULE,fcitx
# env = GTK_IM_MODULE,fcitx
env = MOZ_ENABLE_WAYLAND,1

# Chromium/Electron系アプリをWaylandでネイティブ動作させる
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = NIXOS_OZONE_WL,1
