################
# ウィンドウルール
################
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# すりガラス効果(要改善)
windowrule {
    name = glass-kitty
    match:class = kitty
    opacity = 0.85 0.7
}

windowrule {
    name = glass-vscode
    match:class = ^(code|Code|antigravity|Antigravity)$
    opacity = 0.95 0.85
}

windowrule {
    name = glass-browser
    match:class = ^(vivaldi|Vivaldi|firefox|Firefox|chromium|Chromium|google-chrome|brave-browser)$
    opacity = 0.95 0.85
}

# layerrule = blur on, match:namespace waybar
layerrule {
    name = wlogout_blur
    match:namespace = wlogout
    blur = true
}

layerrule {
    name = wofi_blur
    match:namespace = wofi
    blur = true
}
